import streamlit as st
import google.generativeai as genai
import PyPDF2
from pptx import Presentation
import json
import re

# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(page_title="AI Study Buddy", page_icon="🎓", layout="wide")

# Custom CSS for a clean, modern web design
st.markdown("""
<style>
    .main-header {
        font-size: 2.8rem;
        color: #2c3e50;
        text-align: center;
        font-weight: 700;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #7f8c8d;
        text-align: center;
        margin-bottom: 2rem;
    }
    .stButton>button {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        font-weight: bold;
        border-radius: 8px;
        padding: 0.5rem 1rem;
    }
    .stButton>button:hover {
        background-color: #45a049;
    }
</style>
""", unsafe_allow_html=True)


# ==========================================
# 2. HELPER FUNCTIONS
# ==========================================
def extract_text_from_pdf(uploaded_file):
    """Extracts text from an uploaded PDF file."""
    text = ""
    try:
        pdf_reader = PyPDF2.PdfReader(uploaded_file)
        for page in pdf_reader.pages:
            extracted = page.extract_text()
            if extracted:
                text += extracted + "\n"
    except Exception as e:
        st.error(f"Error reading PDF: {e}")
    return text


def extract_text_from_ppt(uploaded_file):
    """Extracts text from an uploaded PPTX file."""
    text = ""
    try:
        prs = Presentation(uploaded_file)
        for slide in prs.slides:
            for shape in slide.shapes:
                if hasattr(shape, "text"):
                    text += shape.text + "\n"
    except Exception as e:
        st.error(f"Error reading PPTX: {e}")
    return text


def parse_quiz_json(response_text):
    """Safely extracts and parses JSON from the Gemini response."""
    try:
        # Find JSON array using regex in case the AI adds markdown like ```json
        match = re.search(r'\[.*\]', response_text, re.DOTALL)
        if match:
            return json.loads(match.group(0))
        return json.loads(response_text)
    except Exception as e:
        st.error("Failed to parse the quiz generated by AI. Please try generating again.")
        return None


# ==========================================
# 3. SESSION STATE INITIALIZATION
# ==========================================
# We use session state to remember variables across app interactions (button clicks)
if "extracted_text" not in st.session_state:
    st.session_state.extracted_text = ""
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "chat_session" not in st.session_state:
    st.session_state.chat_session = None
if "quiz_data" not in st.session_state:
    st.session_state.quiz_data = None
if "quiz_submitted" not in st.session_state:
    st.session_state.quiz_submitted = False

# ==========================================
# 4. SIDEBAR (Configuration & Upload)
# ==========================================
with st.sidebar:
    st.title("🎓 Settings")

    # User inputs their Gemini API Key here
    api_key = st.text_input("Enter Gemini API Key", type="password")

    st.markdown("---")
    st.subheader("📁 Upload Notes")
    uploaded_file = st.file_uploader("Upload PDF or PPTX", type=["pdf", "pptx"])

    if st.button("Process Document"):
        if not api_key:
            st.error("Please enter your Gemini API Key first.")
        elif not uploaded_file:
            st.error("Please upload a file to process.")
        else:
            with st.spinner("Extracting text..."):
                # Extract text based on file type
                if uploaded_file.name.endswith(".pdf"):
                    text = extract_text_from_pdf(uploaded_file)
                elif uploaded_file.name.endswith(".pptx"):
                    text = extract_text_from_ppt(uploaded_file)

                if text.strip():
                    st.session_state.extracted_text = text

                    # Initialize Gemini API
                    genai.configure(api_key=api_key)

                    # Setup AI Model with system instructions containing the notes
                    system_prompt = f"""
                    You are an expert college tutor. Use the following study notes to answer the student's questions. 
                    If the answer is not in the notes, use your general knowledge but mention that it wasn't in the provided document.

                    Notes:
                    {text[:60000]} # Limit to ~60k characters to avoid exceeding standard payload limits
                    """
                    model = genai.GenerativeModel('gemini-3-flash-preview', system_instruction=system_prompt)

                    # Start the chat session
                    st.session_state.chat_session = model.start_chat(history=[])
                    st.session_state.chat_history = []  # Reset UI chat
                    st.session_state.quiz_data = None  # Reset quiz

                    st.success("Document processed successfully! 🎉")
                else:
                    st.error("Could not extract any text from the document.")

# ==========================================
# 5. MAIN APPLICATION UI
# ==========================================
st.markdown('<h1 class="main-header">🎓 AI Study Buddy</h1>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Upload your college notes, chat with your AI tutor, and test your knowledge!</p>',
            unsafe_allow_html=True)

# Create two tabs for the main functionalities
tab1, tab2 = st.tabs(["💬 Chat & Explain", "📝 Take a Quiz"])

# ------------------------------------------
# TAB 1: Chat Interface
# ------------------------------------------
with tab1:
    st.subheader("Chat with your Notes")
    if not st.session_state.chat_session:
        st.info("👈 Please enter your API key and upload a document in the sidebar to start chatting.")
    else:
        # Display previous chat history
        for msg in st.session_state.chat_history:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])

        # Chat input box
        if prompt := st.chat_input("Ask a question about your notes... (e.g., 'Explain the second topic')"):
            # Show user message
            st.session_state.chat_history.append({"role": "user", "content": prompt})
            with st.chat_message("user"):
                st.markdown(prompt)

            # Get AI response
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    try:
                        response = st.session_state.chat_session.send_message(prompt)
                        st.markdown(response.text)
                        st.session_state.chat_history.append({"role": "assistant", "content": response.text})
                    except Exception as e:
                        st.error(f"An error occurred: {e}")

# ------------------------------------------
# TAB 2: Quiz Generation
# ------------------------------------------
with tab2:
    st.subheader("Test Your Knowledge")
    if not st.session_state.extracted_text:
        st.info("👈 Please upload a document first to generate a quiz.")
    else:
        if st.button("Generate 5-Question Quiz 🚀"):
            with st.spinner("Analyzing notes and generating quiz..."):
                try:
                    genai.configure(api_key=api_key)
                    # We use a dedicated model instance for the quiz to keep generation clean
                    quiz_model = genai.GenerativeModel('gemini-3-flash-preview')

                    quiz_prompt = f"""
                    Analyze the following study notes and create a multiple-choice quiz with 5 questions to test understanding.
                    You MUST respond with ONLY a raw JSON array of objects. Do not include markdown formatting (like ```json).

                    Format exactly like this:
                    [
                      {{
                        "question": "Question text?",
                        "options": ["Option A", "Option B", "Option C", "Option D"],
                        "answer": "Option A",
                        "explanation": "Explanation of why Option A is correct."
                      }}
                    ]

                    Notes context:
                    {st.session_state.extracted_text[:40000]}
                    """
                    response = quiz_model.generate_content(quiz_prompt)
                    parsed_quiz = parse_quiz_json(response.text)

                    if parsed_quiz:
                        st.session_state.quiz_data = parsed_quiz
                        st.session_state.quiz_submitted = False
                        st.rerun()  # Refresh page to show the quiz
                except Exception as e:
                    st.error(f"Error generating quiz: {e}")

        # Display the generated quiz
        if st.session_state.quiz_data:
            st.markdown("---")
            with st.form("quiz_form"):
                user_answers = {}
                for i, q in enumerate(st.session_state.quiz_data):
                    st.markdown(f"**Q{i + 1}: {q['question']}**")
                    # Display options using radio buttons
                    user_answers[i] = st.radio("Select answer:", q['options'], key=f"q_{i}", index=None)
                    st.markdown("---")

                submitted = st.form_submit_button("Submit Answers")
                if submitted:
                    st.session_state.quiz_submitted = True

            # Calculate score and show explanations after submission
            if st.session_state.quiz_submitted:
                score = 0
                for i, q in enumerate(st.session_state.quiz_data):
                    if user_answers.get(i) == q['answer']:
                        score += 1

                st.success(f"### You scored {score} out of {len(st.session_state.quiz_data)}!")
                st.balloons()

                # Show detailed review
                st.subheader("Quiz Review:")
                for i, q in enumerate(st.session_state.quiz_data):
                    st.markdown(f"**Q{i + 1}: {q['question']}**")
                    user_ans = user_answers.get(i)
                    correct_ans = q['answer']

                    if user_ans == correct_ans:
                        st.success(f"Your answer: {user_ans} ✅")
                    else:
                        st.error(f"Your answer: {user_ans} ❌")
                        st.info(f"Correct answer: {correct_ans}")

                    st.caption(f"*Explanation:* {q['explanation']}")
                    st.markdown("---")